### ISSUE TITLE
Customize what's shown

### ISSUE THREAD

**Issue by iwasthesword** [allurewebsolutions/wordpress-post-modal#1]
Is there an easy way to customize what's shown inside the modal?
I tried adding a filter to $content like this. It works if you go to the page directly but won't show anything on the modal.

```
add_filter('the_content', 'new_the_content');

function new_the_content( $content )
{
    return "<img src='https://www.google.com.br/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png'>";
}
```

**Comment by allurewebsolutions** [comment]
@iwasthesword If you are trying to have something show persistently above the Post/Page content in the modal, I would work with the JS in https://github.com/allurewebsolutions/wordpress-post-modal/blob/master/public/js/wordpress-post-modal-public.js (line 77).

You can prepend or append content to what's being loaded from the Post/Page: http://stackoverflow.com/a/8808195/3602355

Alternatively (if you don't mind modifying my plugin), you can edit the public function that I wrote that wraps the Post/Page content with the `modal-ready` div: https://github.com/allurewebsolutions/wordpress-post-modal/blob/master/public/class-wordpress-post-modal-public.php

Let me know if I understood what you needed to accomplish.

-Mike

**Comment by iwasthesword** [comment]
@allurewebsolutions yes, that's what I need, thanks! 

I might have to modify the plugin as I need to retrieve some info with php.
