### ISSUE TITLE
popup open fails when link is not direct child of .modal-link

### ISSUE THREAD

**Issue by cantoute** [allurewebsolutions/wordpress-post-modal#12]
I was getting error when a is not direct child of .modal-link as postLink was undifiend

wp-post-modal/public/js/wp-post-modal-public.js

line 228: fixe by replacing  $(this).child('a') by $('a', this)  

var $this = ($(this).attr('href') != null) ? $(this) : $('a', this).first();

**Comment by cantoute** [comment]
Hi,

anyone around?

**Comment by allurewebsolutions** [comment]
Yes, but on vacation. Will look into this when I get back. 

It would greatly help if you could setup two demos where's modal link is a direct child and one where it is not. That would save me the time of confirming myself. 

In any case, I wouldn't be able to merge into WordPress SVN until early October.

**Comment by cantoute** [comment]
i posted a merge request
check it, it's simple and obvious

**Comment by cantoute** [comment]
Checking here before I forget about all this...

So to be specific, the issue is when using page builders (ie BeaverBuilder) when one ads a class to a link, the class isn't added to the parent element but to a wrapper, so this simple fix solves the issue and catches the first link enclosed in any .popup-link wrapper no matter how nested it is.

The fix is elegant and bullet proof, but if not enclosed in next update it's going to brake my friends' site... and we don't want that :)

At same time the fix will make your plugin compatible with all page builders (commonly used these days)
Your plugin is the only one that does the job, it's neat and handy... Thank you for sharing! And I'm just here to try and help.

```javascript
// var $this = ($(this).attr('href') != null) ? $(this) : $(this).children('a').first();
var $this = ($(this).attr('href') != null) ? $(this) : $('a', this).first();
```

**Comment by allurewebsolutions** [comment]
PR #13 has been merged. Thanks for your help!
