### ISSUE TITLE
Doesn't work with custom post type template?

### ISSUE THREAD

**Issue by djmtype** [allurewebsolutions/wordpress-post-modal#2]
This modal works fine with the category post type. 
But when I apply the same class `modal-link` to links in a custom post type template, the modal loads without content. Nothing gets loaded into the `model-content` div.

**Comment by djmtype** [comment]
Nevermind. I see it only wraps `the_content`. Whereas, I'm not utilizing `the_content` in that template. I need to include more than that, like the featured image and ACF fields. So, looking at your tutorial, I'm trying to figure that out.

**Comment by allurewebsolutions** [comment]
Ah, that makes sense. 

To make your custom post type pages display in the modal, you would need to create a wrapper container (if you don't have one already) and give it the ID of `modal-ready`.

Let me know if that works or if you have any problems and we'll take it from there!

**Comment by djmtype** [comment]
Thanks @allurewebsolutions. I figured it out looking further at your tutorial and codepen example.
