### ISSUE TITLE
Modal content is empty

### ISSUE THREAD

**Issue by EvanAgee** [allurewebsolutions/wordpress-post-modal#5]
Hello, thanks for the work on the plugin! I'm having an issue with an empty modal.

Here is my page:
![image](https://cloud.githubusercontent.com/assets/1692674/26516825/760a316c-4252-11e7-9395-9d36cb1d1740.png)

Here is my menu link:
![image](https://cloud.githubusercontent.com/assets/1692674/26516828/83e2a602-4252-11e7-8546-eb29d06f89ef.png)

Here is what's appearing on the page when I click the link:
![image](https://cloud.githubusercontent.com/assets/1692674/26516834/8ee71dbc-4252-11e7-8fe8-8a2b90fad231.png)

Here's the markup:
![image](https://cloud.githubusercontent.com/assets/1692674/26516838/9a887bfc-4252-11e7-8157-b592e6b832c7.png)

Going to look at the code and see if I can find a solution. If so I'll open a PR.

**Comment by allurewebsolutions** [comment]
@EvanAgee 
Sorry for my unreasonably slow response! 

I've merged in your change and have actually made a good amount of other updates to the plugin.

Thank you!!
