### ISSUE TITLE
error 404 in proxy ?

### ISSUE THREAD

**Issue by tibewww** [allurewebsolutions/wordpress-post-modal#7]
Hi, Superb, this is exactly what I'm looking for, thanks !

I've installed the plugin, and added a class class="modal-link" to my href="#"

on click, nothing appear and I have this error which appear in my console

`jquery.js?ver=1.12.4:4 GET https://mysite/category/art-direction/undefined/wp-post-modal/public/includes/proxy.php?url= 404 (Not Found)`

Do you have any idea what should I do to fix it ?

I also tried to keep the <a href="<?php the_permalink() ?>" instead of # but didnt change anythign, this bring me to the page as external and not modal.

Really appreciate any highlite ! Thanks !

**Comment by allurewebsolutions** [comment]
@tibewww 
Thanks for the kind words!

The href of the link has to be the page that you want to be opened in the modal. If it is left blank, it will definitely not work. However, I tested with a blank href and although it showed the empty modal, it didn't give an error.

Can I see your implementation so I can see the error in action and do some debugging?

**Comment by allurewebsolutions** [comment]
@tibewww This issue may have been fixed with some of the newer releases.
